# -*- coding: utf-8 -*-
"""AI Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HyQYWWo9EoeDRZWkQRp1L-9czQ1ilWPd

Import dataset and libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import os
import cv2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from xgboost import XGBClassifier
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.optimizers import Adam

print("Libraries Loaded. TensorFlow Version:", tf.__version__)

"""Module 02 for identify breaast cancer using clinical data (XGBoost)"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from tensorflow.keras.preprocessing import image
from google.colab import files
import io


print("--- Step 1: Loading & Cleaning Data ---")
url_clinical = "https://raw.githubusercontent.com/selva86/datasets/refs/heads/master/BreastCancer.csv"
df_clinical = pd.read_csv(url_clinical)


cols_to_drop = ['Id', 'id', 'ID', 'Unnamed: 32']
for col in cols_to_drop:
    if col in df_clinical.columns:
        df_clinical.drop(col, axis=1, inplace=True)
        print(f"Dropped column: {col}")


le = LabelEncoder()
df_clinical['Class'] = le.fit_transform(df_clinical['Class'])

# Split Data
X = df_clinical.drop('Class', axis=1)
y = df_clinical['Class']


print(f"Training with {X.shape[1]} features: {list(X.columns)}")


X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_c_scaled = scaler.fit_transform(X_train_c)
X_test_c_scaled = scaler.transform(X_test_c)

# Train XGBoost
print("--- Step 2: Training Clinical Model ---")
model_clinical = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, eval_metric='logloss')
model_clinical.fit(X_train_c_scaled, y_train_c)
print("Clinical Model Trained.")


class BreastCancerSystem:
    def __init__(self, clinical_model, image_model, scaler):
        self.clinical_model = clinical_model
        self.image_model = image_model
        self.scaler = scaler

    def predict_clinical(self, patient_data_array):

        data_reshaped = np.array(patient_data_array).reshape(1, -1)
        scaled_data = self.scaler.transform(data_reshaped)

        prob = self.clinical_model.predict_proba(scaled_data)[0][1]
        pred = 1 if prob > 0.5 else 0
        return pred, prob


if 'model_image' not in globals():
    model_image = None
    print("Image Model not found (Module 02 not run). Image features will be disabled.")

system = BreastCancerSystem(model_clinical, model_image, scaler)
print("System Initialized and Ready.")

from google.colab import drive
drive.mount('/content/drive')

"""Module 02 for identify breaast cancer using images"""

!pip install -q kagglehub

import kagglehub
import os
import glob
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

print("Libraries Loaded.")


print("Downloading Kaggle Dataset (This may take 1-2 minutes)...")

dataset_path = kagglehub.dataset_download('paultimothymooney/breast-histopathology-images')
print(f"Dataset downloaded to: {dataset_path}")



print("Organizing file paths...")

image_paths_0 = glob.glob(os.path.join(dataset_path, '**', '0', '*.png'), recursive=True)
image_paths_1 = glob.glob(os.path.join(dataset_path, '**', '1', '*.png'), recursive=True)

print(f"Found {len(image_paths_0)} Benign images and {len(image_paths_1)} Malignant images.")


SAMPLE_SIZE = 5000


paths_0 = np.random.choice(image_paths_0, SAMPLE_SIZE, replace=False) if len(image_paths_0) > SAMPLE_SIZE else image_paths_0
paths_1 = np.random.choice(image_paths_1, SAMPLE_SIZE, replace=False) if len(image_paths_1) > SAMPLE_SIZE else image_paths_1

# Create a DataFrame
df_0 = pd.DataFrame({'filename': paths_0, 'class': 'BENIGN'})
df_1 = pd.DataFrame({'filename': paths_1, 'class': 'MALIGNANT'})
df_data = pd.concat([df_0, df_1], axis=0).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Training with {len(df_data)} balanced images.")

# Split into Train and Validation
train_df, val_df = train_test_split(df_data, test_size=0.2, random_state=42, stratify=df_data['class'])


datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    horizontal_flip=True,
    vertical_flip=True,
    fill_mode='nearest'
)


train_gen = datagen.flow_from_dataframe(
    train_df,
    x_col='filename',
    y_col='class',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary'
)

val_gen = datagen.flow_from_dataframe(
    val_df,
    x_col='filename',
    y_col='class',
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    shuffle=False
)


print("\nBuilding MobileNetV2 Model...")
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

model_image = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model_image.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

print("Starting Training (This will take a few minutes)...")
history_img = model_image.fit(
    train_gen,
    validation_data=val_gen,
    epochs=5,
    verbose=1
)

print("Real Image Model Trained Successfully!")

"""evaluation code for image model"""

import matplotlib.pyplot as plt


if 'history_img' in globals():
    plt.figure(figsize=(12, 4))

    # Accuracy Plot
    plt.subplot(1, 2, 1)
    plt.plot(history_img.history['accuracy'], label='Train Accuracy')
    plt.plot(history_img.history['val_accuracy'], label='Validation Accuracy')
    plt.title('Deep Learning Model Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # Loss Plot
    plt.subplot(1, 2, 2)
    plt.plot(history_img.history['loss'], label='Train Loss')
    plt.plot(history_img.history['val_loss'], label='Validation Loss')
    plt.title('Deep Learning Model Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()
else:
    print("'history_img' not found. Please run the Imaging Model training cell first.")

"""evaluation matrices"""

from sklearn.metrics import roc_curve, auc, precision_score, recall_score, f1_score, confusion_matrix, accuracy_score
import seaborn as sns

def advanced_evaluation(y_true, y_pred, y_prob, model_name):

    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0) # Sensitivity
    f1 = f1_score(y_true, y_pred, zero_division=0)


    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0


    print(f"--- {model_name} Performance ---")
    print(f"Accuracy:    {acc:.4f}")
    print(f"Precision:   {prec:.4f}")
    print(f"Sensitivity: {rec:.4f}")
    print(f"Specificity: {specificity:.4f}")
    print(f"F1-Score:    {f1:.4f}")
    print("-" * 30)


    plt.figure(figsize=(10, 4))

    # Confusion Matrix
    plt.subplot(1, 2, 1)
    sns.heatmap([[tn, fp], [fn, tp]], annot=True, fmt='d', cmap='Blues')
    plt.title(f'{model_name} Confusion Matrix')

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_true, y_prob)
    roc_auc = auc(fpr, tpr)
    plt.subplot(1, 2, 2)
    plt.plot(fpr, tpr, color='orange', label=f'AUC = {roc_auc:.2f}')
    plt.plot([0, 1], [0, 1], linestyle='--')
    plt.title(f'{model_name} ROC Curve')
    plt.legend()
    plt.show()


print("\n=== CLINICAL MODEL RESULTS ===")
advanced_evaluation(y_test_c, model_clinical.predict(X_test_c_scaled),
                   model_clinical.predict_proba(X_test_c_scaled)[:, 1], "Clinical")


print("\n=== IMAGING MODEL RESULTS ===")
val_gen.reset()
y_prob_img = model_image.predict(val_gen, verbose=0)
y_pred_img = (y_prob_img > 0.5).astype(int).flatten()
advanced_evaluation(val_gen.classes, y_pred_img, y_prob_img, "Imaging")

"""combine the both systems"""

class BreastCancerSystem:
    def __init__(self, clinical_model, image_model, scaler):
        self.clinical_model = clinical_model
        self.image_model = image_model
        self.scaler = scaler
        print("System Initialized: Ready for Hybrid Diagnosis.")

    def predict_clinical(self, patient_data_array):
        """Predicts clinical outcome and probability."""
        scaled_data = self.scaler.transform([patient_data_array])
        prob = self.clinical_model.predict_proba(scaled_data)[:, 1][0]
        pred = 1 if prob > 0.5 else 0
        return pred, prob

    def analyze_patient_history(self, data_array):
        """Analyzes CSV/Numerical Data and prints formatted output"""
        pred, prob = self.predict_clinical(data_array)
        result = "MALIGNANT" if pred == 1 else "BENIGN"
        print(f"""--- Clinical Analysis ---
Diagnosis: {result}
Risk Probability: {prob:.2%} """)
        return result

    def analyze_mammogram(self, image_path):
        """Analyzes Image Data"""
        # Load and preprocess image
        img = tf.keras.utils.load_img(image_path, target_size=(224, 224))
        img_array = tf.keras.utils.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) / 255.0

        prob = self.image_model.predict(img_array, verbose=0)[0][0]
        result = "MALIGNANT" if prob > 0.5 else "BENIGN"

        print(f"--- Imaging Analysis ---\nDiagnosis: {result}\nSeverity Score: {prob:.2%}")
        plt.imshow(img)
        plt.axis('off')
        plt.title(f"Processed Scan: {result}")
        plt.show()
        return result

import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
import io
from tensorflow.keras.preprocessing import image


def interactive_diagnostic_system(system_instance):
    print("\n" + "="*60)
    print("   🏥  BREAST CANCER DIAGNOSTIC SYSTEM (AI-POWERED)")
    print("="*60)

    while True:
        print("\nPlease select a diagnosis method:")
        print("1. 📝 Analyze Clinical Data (Lab Report)")
        print("2. 🖼️ Analyze Mammogram (Image)")
        print("3. 🔄 Comprehensive Check (Both)")
        print("4. ❌ Exit System")

        choice = input("\nEnter your choice (1-4): ").strip()

        if choice == '1':
            run_clinical_diagnosis(system_instance)
        elif choice == '2':
            run_image_diagnosis(system_instance)
        elif choice == '3':
            print("\n--- STARTING COMPREHENSIVE CHECK ---")
            run_clinical_diagnosis(system_instance)
            print("\n...Proceeding to Imaging...")
            run_image_diagnosis(system_instance)
        elif choice == '4':
            print("\nShutting down system. Stay healthy! 👋")
            break
        else:
            print("Invalid selection. Please try again.")

def run_clinical_diagnosis(system_instance):
    print("\n" + "-"*50)
    print("   MODULE A: CLINICAL DATA ANALYSIS")
    print("-"*50)
    print("Options:")
    print("  [A] Manual Entry (Enter patient features step-by-step)")
    print("  [B] Demo Mode (Auto-load a random patient from database)")

    sub_choice = input("Select option (A/B): ").strip().upper()

    patient_data = []

    if sub_choice == 'A':
        print("\n--- Please enter values for the following 9 features (scale 1-10) ---")

        feature_names = [
            "Clump Thickness",
            "Uniformity of Cell Size",
            "Uniformity of Cell Shape",
            "Marginal Adhesion",
            "Single Epithelial Cell Size",
            "Bare Nuclei",
            "Bland Chromatin",
            "Normal Nucleoli",
            "Mitoses"
        ]

        try:
            for feature in feature_names:
                while True:
                    val = input(f"Enter {feature} (1-10): ")
                    try:
                        val_float = float(val)
                        patient_data.append(val_float)
                        break
                    except ValueError:
                        print("Invalid input. Please enter a number.")

            patient_data = np.array(patient_data)

        except Exception as e:
            print(f"Error during input: {e}")
            return

    elif sub_choice == 'B':
        # Pick random patient from test set
        import random
        random_idx = random.randint(0, len(X_test_c) - 1)
        patient_data = X_test_c.iloc[random_idx].values
        actual = y_test_c.iloc[random_idx]
        print(f"\n[DEMO] Loaded Patient ID: {random_idx}")
        print(f"[DEMO] Actual Ground Truth: {'MALIGNANT' if actual==1 else 'BENIGN'}")

    else:
        print("Invalid option.")
        return


    if len(patient_data) == 9:

        pred, prob = system_instance.predict_clinical(patient_data)

        print("\n🔎 --- DIAGNOSTIC REPORT ---")
        print(f"Result:     {'MALIGNANT (Cancer Detected)' if pred == 1 else 'BENIGN (Safe)'}")
        print(f"Confidence: {prob:.2%}")

        if pred == 1:
            print("Recommendation: Immediate consultation with an oncologist is advised.")
        else:
            print("Recommendation: Routine annual screening suggested.")
    else:
        print("Error: Incorrect data shape.")

def run_image_diagnosis(system_instance):
    print("\n" + "-"*50)
    print("   MODULE B: MEDICAL IMAGING ANALYSIS")
    print("-"*50)
    print("Please upload the medical scan image.")

    uploaded = files.upload()

    for fn in uploaded.keys():
        print(f'Processing file "{fn}"...')


        path = fn
        img = image.load_img(path, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0) / 255.0


        prob = system_instance.image_model.predict(img_array, verbose=0)[0][0]


        plt.figure(figsize=(4, 4))
        plt.imshow(img)
        plt.axis('off')
        result_text = "MALIGNANT" if prob > 0.5 else "BENIGN"
        plt.title(f"AI Prediction: {result_text}\nSeverity: {prob:.2%}")
        plt.show()

        print("\n🔎 --- IMAGING REPORT ---")
        print(f"Prediction: {'MALIGNANT' if prob > 0.5 else 'BENIGN'}")
        print(f"Confidence: {prob:.2%}")


interactive_diagnostic_system(system)